#ifndef HARDWARE
#define HARDWARE


//#define HW_STANDARD
#define HW_V5_TD_LOW_CONSUMPTION

#define INPUT 1
#define OUTPUT 0

#define NICO_ON 1
#define NICO_OFF 0

#define EN_MEAS_VBACKUP_PIN_DIRECTION TRISC0
#define EN_MEAS_VBACKUP LATC0

#define EN_3V_PIN_DIRECTION TRISA2
#define EN_3V LATA2

#define CMD_PROTEC_PIN_DIRECTION TRISA4
#define CMD_PROTEC LATA4

#define TX_MICRO_TO_MODEM_PIN_DIRECTION TRISC4
#define TX_MICRO_TO_MODEM LATC4

#define RX_MICRO_TO_MODEM_PIN_DIRECTION TRISC5
#define RX_MICRO_TO_MODEM LATC5

#define CMD_GPS_ON_PIN_DIRECTION TRISC1
#define CMD_GPS_ON LATC1

//#define LED_PIN_DIRECTION TRISA4
//#define LED LATA4

#define VBACKUP_PIN_DIRECTION TRISA5
#define VBACKUP LATA5

#define MEASURE_SOLAR_PIN_DIRECTION TRISC3
#define MEASURE_BACKUP_PIN_DIRECTION TRISC2


#define RX_PIN_DIRECTION TRISA1
#define TX_PIN_DIRECTION TRISA0
#define TX_PIN LATA0

#define PROTECTION_SUPERCAP_ACTIVE CMD_PROTEC_PIN_DIRECTION =OUTPUT

#define PROTECTION_SUPERCAP_INACTIVE CMD_PROTEC_PIN_DIRECTION =INPUT

#define POWER_ON_GPS CMD_GPS_ON_PIN_DIRECTION=OUTPUT //OUTPUT at 0....

#define POWER_OFF_GPS CMD_GPS_ON_PIN_DIRECTION=INPUT //INPUT at HiZ....

#define POWER_ON_VBACKUP VBACKUP=1 
#define POWER_OFF_VBACKUP VBACKUP=0 

#define TD120X

#define T3V_OFF EN_3V=NICO_ON;
#define T3V_ON EN_3V=NICO_OFF;




#endif //HARDWARE